# ~/.config/starship.toml
# https://starship.rs/config/

format = """
$all\
$fill\
$nodejs$python$kubernetes$battery$cmd_duration\
$line_break$character
"""

[fill]
symbol = ' '

[[battery.display]]
threshold = 50

[kubernetes]
disabled = false
# format = 'in [☸️  $context( \($namespace\))]($style) '
