set -g mouse on
set -g default-terminal "tmux-256color"
set -s escape-time 0
set -g history-limit 50000

# Start windows and panes at 1
set -g base-index 1
set -g pane-base-index 1
set-option -g renumber-windows on
set-option -g allow-rename off
set-option -g automatic-rename off

# Remap prefix from 'C-b' to '\'.
unbind C-b
set -g prefix '\'
bind \\ send-prefix

# Reload config quickly
bind r source-file ~/.config/tmux/tmux.conf \; display-message "tmux.conf reloaded"

# Use Alt + Arrow keys to switch windows
bind -n M-Left previous-window
bind -n M-Right next-window

# Vim-like pane navigation with Alt + H/J/K/L
bind -n M-h select-pane -L
bind -n M-j select-pane -D
bind -n M-k select-pane -U
bind -n M-l select-pane -R

# Resize panes with prefix + Shift-H/J/K/L
bind H resize-pane -L 5
bind J resize-pane -D 5
bind K resize-pane -U 5
bind L resize-pane -R 5
bind z resize-pane -Z

# Jump to specific windows with Alt + Number
bind -n M-1 select-window -t 1
bind -n M-2 select-window -t 2
bind -n M-3 select-window -t 3
bind -n M-4 select-window -t 4
bind -n M-5 select-window -t 5
bind -n M-6 select-window -t 6
bind -n M-7 select-window -t 7
bind -n M-8 select-window -t 8
bind -n M-9 select-window -t 9

# Open windows and panes in current directory
bind c new-window -c "#{pane_current_path}"

bind '|' split-window -h -c "#{pane_current_path}"
bind '-' split-window -v -c "#{pane_current_path}"
bind = select-layout even-horizontal
bind + select-layout even-vertical

# Kill panes with Prefix + Backspace
bind BSpace confirm-before -p "kill-pane #P? (y/n)" kill-pane
bind x confirm-before -p "kill-pane #P? (y/n)" kill-pane

# Clear screen and pane history
bind C-l send-keys C-l \; clear-history

# Use Vim keys in copy mode
setw -g mode-keys vi
bind -T copy-mode-vi v send-keys -X begin-selection
bind -T copy-mode-vi y send-keys -X copy-selection-and-cancel

set -g @catppuccin_flavor 'latte'
set -g @catppuccin_window_status_style "rounded"
set -g @catppuccin_window_text " #W"
set -g @catppuccin_window_current_text " #W"

run ~/.config/tmux/plugins/catppuccin/tmux/catppuccin.tmux

# Make the status line pretty and add some modules
set -g status-right-length 100
set -g status-left-length 100
set -g status-left ""
set -g status-right "#{E:@catppuccin_status_application}"
set -ag status-right "#{E:@catppuccin_status_session}"


set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'

run '~/.config/tmux/plugins/tpm/tpm'

